# Dependencies
markdown:  redcarpet
pygments:  true

# Permalinks
permalink:  pretty
relative_permalinks:  true

# Setup
# root:  http://adhocbookclub.github.io
title:  Ad Hoc Book Club


redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
