# Dependencies
markdown:  redcarpet
highlighter:  pygments

# Permalinks
permalink:  pretty

# Setup
# root:  http://adhocbookclub.github.io
title:  Ad Hoc Book Club


redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
